const APPS = [{
    id: 0,
    name: 'Farming Simulator 20',
    desc: 'Realistic Farm Simulation',
    cat: 'Games',
    img: 'https://i.postimg.cc/65JyFb7p/1709735747-farming-simulator-20.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v20/Farming_Simulator_20.apk',
    ver: 'v20',
    sz: '650 MB',
    rt: '4.3',
    cnt: '1.2M',
    about: 'Farming Simulator 20 brings the most complete farming experience to mobile! Drive over 100 authentic farm vehicles.',
    feats: ['100+ farm vehicles', 'Crop farming', 'Animal husbandry', 'Multiplayer mode', 'Open world']
}, {
    id: 1,
    name: 'Picsart Pro',
    desc: 'AI Photo & Video Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/FsTX07QJ/Picsart-26-05-21-13-50-32-520.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v29.8.5/Picsart_29.8.5_.Pro.apk',
    ver: 'v29.8.5',
    sz: '85 MB',
    rt: '4.7',
    cnt: '50M',
    about: "Picsart is the world's #1 creative platform. All Pro features unlocked!",
    feats: ['AI Photo editing', 'Video editor', '1000+ templates', 'Background remover', 'Pro filters']
}, {
    id: 2,
    name: 'CapCut Pro',
    desc: 'Professional Video Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/XvFP1vtH/Picsart-26-05-21-13-51-32-987.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v17.3.0/CapCut_17.3.0.apk',
    ver: 'v17.3.0',
    sz: '120 MB',
    rt: '4.8',
    cnt: '100M',
    about: 'CapCut is the all-in-one video editing app. AI-powered features and trending effects.',
    feats: ['AI video editing', 'Auto captions', 'Trending effects', 'Music library', 'No watermark']
}, {
    id: 3,
    name: 'SnapTube Pro',
    desc: 'Video & Music Downloader',
    cat: 'Tools',
    img: 'https://i.postimg.cc/cHhXPthd/Picsart-26-05-21-13-51-56-844.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v15.4.0/SnapTube_v5.apk',
    ver: 'v15.4.0',
    sz: '28 MB',
    rt: '4.5',
    cnt: '10M',
    about: 'Download videos from YouTube, Facebook, Instagram and 50+ platforms.',
    feats: ['50+ platforms', 'HD download', 'MP3 extraction', 'Fast speed', 'No ads']
}, {
    id: 4,
    name: 'Meitu Pro',
    desc: 'AI Photo Retouch',
    cat: 'Editors',
    img: 'https://i.postimg.cc/LsBTZgcp/Picsart-26-05-21-13-53-59-866.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v9.7.0.6/Meitu_9.7.0.6.apk',
    ver: 'v9.7.0.6',
    sz: '95 MB',
    rt: '4.6',
    cnt: '20M',
    about: 'AI-powered beauty camera and photo editor.',
    feats: ['AI skin retouch', 'Selfie beauty', 'Collage maker', 'Artistic filters', 'Makeup effects']
}, {
    id: 5,
    name: 'TeraBox Premium',
    desc: 'Cloud Storage',
    cat: 'Tools',
    img: 'https://i.postimg.cc/J7gb0Qs8/Picsart-26-05-21-13-54-50-591.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v8.6.0/TeraBox_pro.apk',
    ver: 'v8.6.0',
    sz: '45 MB',
    rt: '4.4',
    cnt: '5M',
    about: '1TB of FREE cloud storage. Backup and share files easily.',
    feats: ['1TB free storage', 'Auto backup', 'File sharing', 'Password folder', 'Fast speed']
}, {
    id: 6,
    name: 'Hypic Pro',
    desc: 'AI Photo Editing Tool',
    cat: 'Editors',
    img: 'https://i.postimg.cc/6qG4nD8y/Picsart-26-05-21-13-55-22-982.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v8.5.0/Hypic_8.5.0_.Pro.apk',
    ver: 'v8.5.0',
    sz: '72 MB',
    rt: '4.5',
    cnt: '3M',
    about: 'Powerful AI photo editor with professional tools.',
    feats: ['AI enhancement', 'Background removal', 'Pro filters', 'Skin smooth', 'Object removal']
}, {
    id: 7,
    name: 'Gcam LMC 8.4',
    desc: 'Pixel Camera Mod',
    cat: 'Tools',
    img: 'https://i.postimg.cc/Fzt3Wr57/Picsart-26-05-21-13-55-54-841.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v8.4.0/LMC8.4.apk',
    ver: 'v8.4',
    sz: '62 MB',
    rt: '4.7',
    cnt: '8M',
    about: 'Google Camera mod with Night Sight and HDR+ processing.',
    feats: ['Google HDR+', 'Night Sight', 'Astrophotography', 'Portrait mode', 'RAW capture']
}, {
    id: 8,
    name: 'KineMaster Pro',
    desc: 'Advanced Video Editing',
    cat: 'Editors',
    img: 'https://i.postimg.cc/j5yLjymt/Picsart-26-05-21-13-56-22-186.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v8.1.3/KineMaster_8.1.3.36292.GP.apk',
    ver: 'v8.1.3',
    sz: '110 MB',
    rt: '4.6',
    cnt: '30M',
    about: 'Full-featured video editor with multi-layer editing and chroma key.',
    feats: ['Multi-layer editing', 'Chroma key', 'Speed control', 'Sound effects', 'No watermark']
}, {
    id: 9,
    name: 'ReLens DSLR Pro',
    desc: 'DSLR Bokeh Camera',
    cat: 'Editors',
    img: 'https://i.postimg.cc/YqDqMX08/Picsart-26-05-21-13-57-04-606.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v7.8.0/ReLens.Pro.apk',
    ver: 'v7.8.0',
    sz: '55 MB',
    rt: '4.4',
    cnt: '2M',
    about: 'Give your photos a professional DSLR look with bokeh effects.',
    feats: ['DSLR bokeh', 'Real-time preview', 'Cinematic blur', 'Portrait mode', 'Lens styles']
}, {
    id: 10,
    name: 'Duolingo Pro',
    desc: 'Language Learning',
    cat: 'Tools',
    img: 'https://i.postimg.cc/VNBxL6g3/Picsart-26-05-21-13-58-56-547.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v7.6.0/Duolingo.Pro.apk',
    ver: 'v7.6.0',
    sz: '38 MB',
    rt: '4.8',
    cnt: '25M',
    about: 'Learn 40+ languages with gamified lessons.',
    feats: ['40+ languages', 'Gamified learning', 'Daily streaks', 'Offline lessons', 'AI path']
}, {
    id: 11,
    name: 'Photoshop Express',
    desc: 'Adobe Photo Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/dVcNkFhC/Picsart-26-05-21-13-59-54-576.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v5.3.0/Photoshop_v17.9.22.apk',
    ver: 'v17.9',
    sz: '88 MB',
    rt: '4.5',
    cnt: '40M',
    about: 'Fast photo editor with one-touch filters and collage maker.',
    feats: ['One-touch fix', 'Color adjustments', 'Noise reduction', 'Perspective fix', 'Cloud sync']
}, {
    id: 12,
    name: 'Motion Ninja Pro',
    desc: 'Video Editor & Animator',
    cat: 'Editors',
    img: 'https://i.postimg.cc/k4LzTbgw/Picsart-26-05-21-14-00-27-115.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v5.1.0/Motion.Ninja.Pro.apk',
    ver: 'v5.1.0',
    sz: '78 MB',
    rt: '4.4',
    cnt: '1.5M',
    about: 'Keyframe animations and cinematic transitions.',
    feats: ['Keyframe animation', 'Motion blur', 'Transitions', 'Speed ramp', 'Multi-track']
}, {
    id: 13,
    name: 'Alight Motion Pro',
    desc: 'Motion Graphics',
    cat: 'Editors',
    img: 'https://i.postimg.cc/1z2vSZ13/Picsart-26-05-21-14-01-11-647.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/5.0.273/Alight.Motion_5.0.273.1028417.apk',
    ver: 'v5.0.273',
    sz: '130 MB',
    rt: '4.7',
    cnt: '15M',
    about: 'Professional motion graphics app for mobile.',
    feats: ['Professional animation', 'Vector support', 'Multi-layer', 'Color grading', 'No watermark']
}, {
    id: 14,
    name: 'YouTube Lite',
    desc: 'Lightweight Streaming',
    cat: 'Streaming',
    img: 'https://i.postimg.cc/Kv0rFynX/Picsart-26-05-21-14-03-58-172.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v4.7.0/YouTube.Lite.apk',
    ver: 'v4.7.0',
    sz: '18 MB',
    rt: '4.3',
    cnt: '5M',
    about: 'YouTube Lite for low-end devices with minimal data.',
    feats: ['Low data', 'Fast loading', 'Background play', 'Ad-free', 'Lightweight']
}, {
    id: 15,
    name: 'PrettyUp Pro',
    desc: 'Video Beauty Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/d19ZB8BR/Picsart-26-05-21-14-06-22-519.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v4.3.0/PrettyUp.Pro.apk',
    ver: 'v4.3.0',
    sz: '65 MB',
    rt: '4.3',
    cnt: '2M',
    about: 'AI beauty editor for videos in real-time.',
    feats: ['Face slimming', 'Body reshape', 'Skin smooth', 'Eye enlargement', 'Beauty filters']
}, {
    id: 16,
    name: 'Remini AI',
    desc: 'Photo Enhancer',
    cat: 'Tools',
    img: 'https://i.postimg.cc/kX2D6rk0/Picsart-26-05-21-14-07-44-368.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/3.7.1301/Remini_3.7.1301.202520348.apk',
    ver: 'v3.7.1',
    sz: '42 MB',
    rt: '4.6',
    cnt: '10M',
    about: 'AI enhances blurry photos to HD quality.',
    feats: ['AI enhancement', 'Old photo restore', 'Face sharpen', 'HD upscaling', 'Blur removal']
}, {
    id: 17,
    name: 'Captions AI',
    desc: 'Auto Subtitle Maker',
    cat: 'Editors',
    img: 'https://i.postimg.cc/fbDwv1r9/Picsart-26-05-21-14-08-08-748.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v3.5.0/Captions.AI.-.Captune.apk',
    ver: 'v3.5.0',
    sz: '35 MB',
    rt: '4.5',
    cnt: '1M',
    about: 'Auto-generate accurate subtitles for videos.',
    feats: ['Auto speech-to-text', 'Multi-language', 'Animated styles', 'Custom fonts', 'Social export']
}, {
    id: 18,
    name: 'Magic Eraser Pro',
    desc: 'Object Remover',
    cat: 'Tools',
    img: 'https://i.postimg.cc/7PGfbrfs/595115558-84821fb8-69cf-48d0-9857-b46282dfd5c3.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v3.3.20/Magic.Eraser_3.3.20_.Pro.apk',
    ver: 'v3.3.20',
    sz: '48 MB',
    rt: '4.5',
    cnt: '3M',
    about: 'AI removes unwanted objects with precision.',
    feats: ['AI removal', 'Background eraser', 'Touch-up', 'Batch process', 'High quality']
}, {
    id: 19,
    name: 'InShot Pro',
    desc: 'HD Video Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/gcZ2myRT/Picsart-26-05-21-14-08-52-015.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/2.196.1529/InShot_2.196.1529.apk',
    ver: 'v2.196',
    sz: '80 MB',
    rt: '4.7',
    cnt: '35M',
    about: 'Video editor for Instagram, TikTok and YouTube.',
    feats: ['Video trim', 'Add music', 'Text & stickers', 'Speed control', 'No watermark']
}, {
    id: 20,
    name: 'VN Video Editor',
    desc: 'Vlog & Movie Maker',
    cat: 'Editors',
    img: 'https://i.postimg.cc/13CQp4wq/Picsart-26-05-21-14-09-56-828.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/2.14.0/VN.-.Video.Editor_2.14.0.apk',
    ver: 'v2.14.0',
    sz: '95 MB',
    rt: '4.6',
    cnt: '12M',
    about: 'Free professional video editor with multi-track timeline.',
    feats: ['Multi-track', 'Keyframe animation', 'Color grading', 'No watermark', 'Pro transitions']
}, {
    id: 21,
    name: 'PixelLab Pro',
    desc: 'Text on Pictures',
    cat: 'Editors',
    img: 'https://i.postimg.cc/nh6dbJty/Picsart-26-05-21-14-10-38-356.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/2.1.9/PixelLab_2.1.9.apk',
    ver: 'v2.1.9',
    sz: '32 MB',
    rt: '4.5',
    cnt: '5M',
    about: 'Best app for adding text to pictures with 500+ fonts.',
    feats: ['500+ fonts', '3D text effects', 'Shadow & glow', 'Custom stickers', 'Templates']
}, {
    id: 22,
    name: 'Spotify Lite Mod',
    desc: 'Lightweight Music',
    cat: 'Streaming',
    img: 'https://i.postimg.cc/BvTBrPpM/Picsart-26-05-21-14-11-21-760.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v2.0.8/Spotify.Lite_2.0.8.apk',
    ver: 'v2.0.8',
    sz: '15 MB',
    rt: '4.4',
    cnt: '8M',
    about: 'Lighter Spotify for streaming music and podcasts.',
    feats: ['Low data', 'Small size', 'Offline listen', 'Podcast', 'Background play']
}, {
    id: 23,
    name: 'Winkit Pro',
    desc: 'AI Video Enhancer',
    cat: 'Tools',
    img: 'https://i.postimg.cc/4NjvnQFz/Picsart-26-05-21-14-11-47-748.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v2.0.2/Winkit_2.0.2.apk',
    ver: 'v2.0.2',
    sz: '58 MB',
    rt: '4.3',
    cnt: '800K',
    about: 'AI enhances videos professionally.',
    feats: ['AI enhance', 'Noise reduce', 'Stabilize', 'Color fix', 'HD upscaling']
}, {
    id: 24,
    name: 'LMC 8.4 Filters',
    desc: 'GCam Presets',
    cat: 'Tools',
    img: 'https://i.postimg.cc/4d3HWYSz/Picsart-26-05-21-14-12-43-028.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v2.0.0/LMC-8.4.filter.zip',
    ver: 'v2.0.0',
    sz: '12 MB',
    rt: '4.6',
    cnt: '500K',
    about: 'Premium camera presets for Google Camera mod.',
    feats: ['Premium XML', 'Multiple modes', 'Night presets', 'Portrait opt', 'Easy install']
}, {
    id: 25,
    name: 'Photoroom Mod',
    desc: 'AI Studio Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/QCTtz1kx/Picsart-26-05-21-14-13-08-735.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v2/Photoroom.M0D.v2.apk',
    ver: 'v2.0',
    sz: '68 MB',
    rt: '4.6',
    cnt: '4M',
    about: 'AI creates professional product photos.',
    feats: ['BG removal', 'Studio backgrounds', 'Product photos', 'AI portrait', 'Batch edit']
}, {
    id: 26,
    name: 'Utool AI Enhancer',
    desc: 'Video Quality Fixer',
    cat: 'Tools',
    img: 'https://i.postimg.cc/DzxcgJcG/Picsart-26-05-21-14-13-34-305.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v1.172.78/AI.Video.Enhancer.-.Utool_1.172.78.apk',
    ver: 'v1.172',
    sz: '75 MB',
    rt: '4.4',
    cnt: '600K',
    about: 'AI upscales low-res videos to HD quality.',
    feats: ['AI upscaling', 'Frame interpolation', 'Blur fix', 'Color enhance', 'Batch process']
}, {
    id: 27,
    name: '24FPS Video Editor',
    desc: 'Cinematic Editor',
    cat: 'Editors',
    img: 'https://i.postimg.cc/k4kK1xR2/595407726-fd45314b-10a8-4a79-8b1d-ec93e6a97e9c.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v1.0.0/24FPS.Video.Editor.apk',
    ver: 'v1.0.0',
    sz: '52 MB',
    rt: '4.3',
    cnt: '300K',
    about: 'Cinematic video editor for filmmakers.',
    feats: ['Cinematic grading', 'Film grain', 'Anamorphic', 'LUT support', '4K export']
}, {
    id: 28,
    name: 'Lightroom Mobile',
    desc: 'Pro Color Grading',
    cat: 'Editors',
    img: 'https://i.postimg.cc/Y0KLfMTd/Picsart-26-05-21-14-14-33-319.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/11.3.3/lightroom-11.3.3-an1.com.apk',
    ver: 'v11.3.3',
    sz: '102 MB',
    rt: '4.7',
    cnt: '45M',
    about: 'Adobe Lightroom for professional RAW editing.',
    feats: ['RAW editing', 'Advanced grading', 'AI masking', 'Preset library', 'Cloud sync']
}, {
    id: 29,
    name: 'Netflix Premium',
    desc: 'Movies & TV Streaming',
    cat: 'Streaming',
    img: 'https://i.postimg.cc/xTgqqvjy/593674587-aa789283-0ee2-4970-a4d2-e1b574233ea9.png',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/v9.75.0/Netflix_9.75.0.apk',
    ver: 'v9.75.0',
    sz: '55 MB',
    rt: '4.5',
    cnt: '80M',
    about: "World's leading streaming service in 4K.",
    feats: ['4K Ultra HD', 'Offline download', 'Multi profiles', 'Originals', 'Ad-free']
}, {
    id: 30,
    name: 'SUBR Plugin',
    desc: 'System Utility',
    cat: 'Tools',
    img: 'https://i.postimg.cc/NfGjhK8m/594010530-be7fab84-dfe1-4149-8ef1-fbff07ad6aea.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/5.3.46/SUBR_5.3.46.apk',
    ver: 'v5.3.46',
    sz: '22 MB',
    rt: '4.2',
    cnt: '200K',
    about: 'System utility for better app performance.',
    feats: ['System optimize', 'Background service', 'Performance boost', 'Battery save', 'Lightweight']
}, {
    id: 31,
    name: 'Minecraft',
    desc: 'Premium Sandbox Game',
    cat: 'Games',
    img: 'https://i.postimg.cc/vBzwXvNk/593673904-6b1947b8-4e5a-4971-beb4-0b40dd14c289.jpg',
    apk: 'https://github.com/xvideoworld/Nyxora/releases/download/1v1/Minecraft_premium.apk',
    ver: 'Premium',
    sz: '950 MB',
    rt: '4.9',
    cnt: '100M',
    about: "Best-selling game ever. Build, survive and explore infinite worlds.",
    feats: ['Infinite world', 'Creative & Survival', 'Multiplayer', 'Marketplace', 'Updates']
}];
